config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'account', to: 'pages#account'
  get 'projects/index'

  resources :projects do
    resources :pledges
 end 

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
  end

 

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :projects
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	belongs_to :project
	belongs_to :user

	before_validation :generate_uuid!, :on => :create
	validates_presence_of :amount,:user_id
	after_create :check_if_funded

	private


#changes the project's status to "funded" if the total amount pledged is 
#greater or equal to the project's goal.
	def check_if_funded 
		project.funded! if project.total_amount >= project.goal
	end

	def generate_uuid!
		begin
			self.uuid = SecureRandom.hex(16)
		end while Pledge.find_by(:uuid => self.uuid).present? # to avoid duplication on the database
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :pledges
	belongs_to :category

	validates_presence_of :title, :summary, :description, :image, :goal, :user_id

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	has_attached_file :resource
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/



	#has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  

	#gets all the pledges and sums up total amount.
	def total_amount
		pledges.map(&:amount).inject(0, :+)
	end


	def days_to_go
		(self.expiration_date.to_date - Date.today).to_i
	end


	def self.search(search)
		if search 
			where(["title LIKE?", "%#{search}%"])
		else
			all
		end
	end

private

	def start_project
		self.expiration_date = 3.months.from_now
	end




end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
  has_many :pledges

  validates_presence_of :email

  def self.from_omniauth(auth)
    p auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      user.image = auth.info.image
    end
  end


  def self.new_with_sessions(params, session) #check if there is a session with devise user attributes
  	if session[ "devise.user_attributes" ]
  		new(session[ "devise.user_attributes" ], without_protection: true) do |user|
  			user.attributes = params
  			user.valid?
  			end
  		else
  			super
  		end
  end

  def password_required?
  	super && provider.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	
	

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication
		else
			redirect_to new_user_registration_url
		end
	end

	  def failure
	    redirect_to root_path
	  end
		
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #make sure users are logged in
before_action :authenticate_user!, only: [:account]	
  def home
  	if current_user
  		redirect_to account_path
  	end
  end

  def about
  end

  def account
    #fetches all the projects that bellow to a current owner
   	@projects=current_user.projects
  end

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_project
	
	#project owner ability to see how many people pledges for a project created
	def index
		@pledges = @project.pledges
		respond_to do |format| 
			format.html
		end
	end

	def new
	  @pledges =current_user.pledges.build
		#@pledge = @project.find(params[:project_id])
		#@pledge = @project.pledges.new
		respond_to do |format|
			format.html
		end
	end
	
	def create  
	 # @pledge = current_user.pledges.build(create_pledge_params)
	 @project = Project.find_by_id(params[:project_id])
	 @pledge = @project.pledges.create(amount: params[:pledge]["amount"], user: current_user)
	  respond_to do |format|
	    if @project.user != current_user &&
	    	current_user == Project.find(@project)
		        	flash.now[:error] = "Pledge is invalid"
	        	format.html {render :new }
	        		format.json { render json: @pledge.errors, status: :unprocessable_entity }
	        	
    	else
			#current_user.update(project_id: result.pledge.id)
          	format.html { redirect_to project_pledge_path(@project, @pledge), notice: "Your pledge was successfully created." }
        	# format.html { render :show }
        	format.json { render :show, status: :ok, location: @pledge }
	    end     
	  end
	end

 def show
 	@project = Project.find_by_id(params[:project_id])
 	@pledge = Pledge.find_by_id(params[:id])
 end

	private

	def create_pledge_params
		params.require(:pledge).permit(:amount, :user_id, :project_id, :expiration_date, :status)
	end

	def set_pledges
		@pledges = @project.pledges
	end

	def set_project
		@project = Project.find(params[:project_id])
	end

	def set_amount
		@amount = Pledge.find(params[:amount].to_i)
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show] #users are able to see all projects and individial /show page
	before_action :set_project, only: [:show, :edit, :update, :destroy]


	def index
		if params[:category].blank? #display all without filtering
			@projects = Project.search(params[:search])
		else
			@category_id = Category.find_by(name: params[:category]).id #FILTER DEPENDS ON WHAT IS THE PARAM
			@projects = Project.where(:category_id => @category_id)
		end
		#@projects = Project.all.order("created_at DESC")
		#@displayed.projects = Project.take(3) for a dynamic carroussel which I am not going to implement 
	end

	def show

	end

	def new
		@project = Project.new
		#@projects = current_user.projects.build
		@categories = Category.all.map{ |c| [c.name, c.id]} #when select_tag is created for a dropdown menu in the form partial
															#options_for_select requires an array of arrays, which will be the 
															#text for dropdown (its name) and the value in the db(id attribute)
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id]} 
	end

	def create #building out projects from the current user
		#@project=Project.create(project_params)
		@project = current_user.projects.build(project_params)
		@project.category_id = params[:category_id]

		respond_to do |format|
			if @project.save
				format.html { redirect_to @project, notice: "Project was succesfully created."}
				format.json { render :show, status: :ok, location: @project }
			else
				format.html { render :new }
				format.json { render json: @project.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		@project.category_id = params[:category_id]
		respond_to do |format|
			if @project.update(project_params)
				format.html { redirect_to @project, notice: "Project was succesfully updated."}
				format.json { render :show, status: :ok, location: @project }
			else
				format.html { render :edit }
				format.json { render json: @project.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@project.destroy
		respond_to do |format|
			format.html { redirect_to root_path, notice: "Project was succesfully removed."}
			format.json { head :no_content }
		end
	end

private

	def set_project #gets the projects from the params for actions show, edit, update and destroy
		@project = Project.find(params[:id])
	end

	def set_category
 	 @category = Category.includes(:projects).find(params[:id])
	end


	def project_params
		params.require(:project).permit(:title, :summary, :description, :goal, :expiration_date, :category_id, :image, :resource)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message |%>
	<div class="alert alert-info fade-in text-center">
		<button class="close" data-dismiss="alert">x</button>
			<%= message %>
	</div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "socialweaver", root_path, class: "navbar-brand" %>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Create", new_project_path %><span class="sr-only">(current)</span></a></li>
        <li><%= link_to "Explore", projects_path %></li>
        <li><%= link_to "About", about_path %></li>   
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
          <% if user_signed_in? %>
            <li><p>Hello, <%= current_user.email %></p></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Home", account_path %></li>
                <li><%= link_to "Profile", "#" %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create a Project", new_project_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path, class: "btn btn-default btn-md" %></li>
            <li><%= link_to "Login with Facebook", user_facebook_omniauth_authorize_path, class: "btn btn-default btn-md" %></li>
          <% end %>
      </ul>

      <form class="navbar-form navbar-right">
        <div class="form-group">
          <%= form_tag projects_path, method: :get, class: 'navbar-form navbar-right' do %>
          <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'search for projects' %>
          <%= submit_tag "Search", class: 'btn btn-default' %>
          <% end %>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialweaver</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="col-md-6 col-md-offset-3">
	<%= render 'layouts/flash' %>
</div>


<%= yield %>


</body>
</html>

app/views/pages/_jumbotron.html.erb
<div class="jumbotron">
	<div class="container text-center">
		<video class="video-background" autoplay="" loop="" class="fillWidth fadeIn animated" poster="https://s3-us-west-2.amazonaws.com/coverr/poster/Traffic-blurred2.jpg" id="video-background">
			<source src="https://s3-us-west-2.amazonaws.com/coverr/mp4/Traffic-blurred2.mp4" type="video/mp4">Your browser does not support the video tag. I suggest you upgrade your browser.
		</video>
	</div>
</div>

app/views/pages/about.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>About</h1>
			<p>We crowdsource</p>
		</div>
	</div>
</div>

app/views/pages/account.html.erb
<div class="container">
	<div class="row">
		<h1 class="text-center">Welcome, aboard!</h1>
		
		<div class="col-md-4">
			
				<h3 class="text-center">Your Projects<%= link_to "New Project", new_project_path, class: "btn btn-default btn-sm" %>
					
				</h3>				
					
					<table class="table table-condensed table-striped">
						<thead>
							<tr>
								<th>ID</th>
								<th>Project Name</th>
								<th>Goal</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<% @projects.each do |project| %>
							<tr>
								<td><%= project.id %></td>
								<td><%= link_to project.title, project_path(project) %></td>
								<td><%= project.goal %></td>
								<td><%= link_to "View Project Backers", "#", class: "btn btn-default btn-sm" %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
		</div>
	
		<div class="col-md-4">
		
				<h3 class="text-center">Backed Projects</h3>

					<table class="table table-condensed">
						<thead>
							<tr>
								<th>ID</th>
								<th>Project Name</th>
								<th>Donation</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
					</tbody>
					</table>

		</div>

		<div class="col-md-4">
		
				<h3 class="text-center">Skills Offered</h3>

			
		
		</div>

	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
		<div class="video">
		<video class="video-background" autoplay="true" loop="true" class="fillWidth fadeIn animated"  width="100%" poster="https://s3-us-west-2.amazonaws.com/coverr/poster/Traffic-blurred2.jpg" id="video-background">
			<source src="https://s3-us-west-2.amazonaws.com/coverr/mp4/Traffic-blurred2.mp4" type="video/mp4">Your browser does not support the video tag. I suggest you upgrade your browser.
		</video>
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
					<h1>Together Civic Life</h1>
				

						<div class="button-video">
						<p><%= link_to "What is Crowdfunding?", "#", class: "btn btn-default btn-lg" %></p>
						</div>
						</div>
					</div>
				</div>
</div>

app/views/pledges/_form.html.erb
<div class="row">
	<h4>How much will you pledge?</h4>
</div>


		<%= simple_form_for @pledges, url: {controller: :pledges, action: :create}, method: :post do |f| %>
		<fieldset>
		<%= f.input :amount, placeholder: "enter your pledge amount:", input_html: {value: @project.try(:value), required: true} %>
		
		</fieldset>

		<div class="actions">
		<%= f.button :submit %>
		</div>

<% end %>

app/views/pledges/_pledge.html.erb
<tr>
	<th scope="row"><%= pledge.id %>
	<td><% link_to @pledge.project.title, project_path(pledge.project) %></td>
	<td><% number_to_currency(@pledge.amount, unit: "$") %></td>
</th>

app/views/pledges/index.html.erb
<h1>pledges index -only project owner can see this: </h1>


<div class="project-intro">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive">				
					
					<table class="table table-hover">
						<thead>
							<tr>
								<th>ID</th>
								<th>Project</th>
								<th>Pledge</th>
							</tr>
						</thead>

						<tbody>
							<%if @pledges.any? %>
							<% @pledges.each do |pledge| %>
							<%= render 'pledge', pledge: pledge %>
							<% end %>
							<% else %>

							<tr>
								<td colspan="4">There are no pledges available</td>
							</tr>

							<% end %>
						</tbody>
					</table>

				</div>
			</div>
		</div>	
	</div>	
</div>

app/views/pledges/new.html.erb
<div class="project-intro">
<div class="container">

<div class="row-pledges">
	<div class="col-sm-5 col-sm-offset-2">
		<h4>Selected Project</h4>
		<p class="project-title"><%= link_to @project.title, project_path(@project) %></p>
		
			<div class="thumbnail">
			<%= link_to image_tag(@project.image_url, alt: @project.title, class: 'img-responsive'), project_path(@project) %>
			</div>
		<p><%= @project.goal %></p>
	</div>

	<div class="pledges-box">
		<div class= "col-sm-3 col-sm-offset-1">
			

		<%= render 'form' %>
		<br>
		<div class="message">
			<p>Your won't be charged this time. You will be charged only if the project reaches its goal!</p>
			</div>
		</div>
	</div>
</div>




</div>
</div>

app/views/pledges/show.html.erb
<div class="col-md-12">
<h1> Thank you for your pledge</h1>
<p>You will be charged <strong><%= number_to_currency(@pledge.amount, unit: '$', precision: 2)%></strong> if the project <%= @project.title %> reaches its goal!</p>
</div>

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: {:multipart => true, class: 'form-horizontal'}) do |f| %>
	<%= f.input :title %>
	<%= f.label :category %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category")%><br>
	<%= f.input :summary, label:"Brief Description", placeholder: "brief description" %>
	<%= f.input :description, as: :wysihtml5 %>
	<%= f.input :image, as: :file %>
	<%= f.input :goal %>
	<%= f.input :expiration_date%>
	
	

	<div class="actions">
		<%= f.button :submit %>
	</div>
<% end %>
<br>

app/views/projects/_project.html.erb
<div class="col-md-4 col-sm-6 col-xs-12">
	<div class="thumbnail">
		<%= link_to image_tag(project.image_url, alt: project.title, class: 'img-responsive'), project_path(project) %>
			<div class="caption">
				<p class="text-uppercase"><%= link_to project.title, project_path(project) %></p>
				<p><%= project.category.name %></p>
				<p>Goal $<span><%= project.goal %></span></p>
				
				<div class="project-bar">
					<div class="progress">
						<div class="progress-bar-sucess" role="progressbar" aria-valuenow="100%" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
							<span class="sr-only">100% Complete</span>
						</div>
					</div>
				</div>

				<div class="stats">
					<div>
						<p>100%<span>funded</span></p>
						<p>$1000 <span>pledged</span></p>
						<p>10 <span>days to go</span></p>
					</div>
				</div>

				<div class="link text-center">
				<p><%= link_to "View Project", project_path(project), class: 'btn btn-success btn-offset-right' %></p>
				</div>
			
			</div><!--end of caption-->
	</div>
</div>

app/views/projects/edit.html.erb
<div class="container">
	<h1>Edit Project</h1>
	
	<%= simple_form_for(@project, html: { :multipart => true, class: 'form-horizontal'}) do |f| %>
	<%= f.input :title %>
	<%= f.select :category_id, @categories %><br>
	<%= f.input :summary, label:"Brief Description" %>
	<%= f.input :description, as: :wysihtml5 %>
	<%= f.input :image, as: :file %>
	<%= f.input :goal %>
	<%= f.input :expiration_date %>


	<div class="actions">
		<%= f.button :submit %>
	</div>

<%end %>

	<%= link_to 'Show', @project %>
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<div class="container"> 
	
	<div class="row">
		
			<% if @projects.count == 0 %>
			<div class="text-center">
				<h2>There is no projects in this category.</h2>
				<h3>Would you like to create your first project?</h3>
			</div>
			<div class="col-md-4 col-md-offset-4">
				<p><%= link_to "Create", new_project_path, class: "btn btn-success btn-block" %></p>
			</div>
		
	</div>

			<% else %>

	<div class= "row">
		<h3 class="text-center">Feel free to explore the projects!!</h3>
	<div>

		<div class= "row">
			<div class="col-md-3">

				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category]== category.name %>">
								<%= link_to category.name, projects_path(category: category.name), class: "link" %>
							</li>
							<% end %>
						</ul>
					</li>
				</ul>

			</div>
</div>
	<div class="row">
	
			<%= render @projects %>
	
	<div>
		
<% end %>
</div>

app/views/projects/new.html.erb
<div class="container">
	<div class="row">
		<%= link_to "Back", account_path %>
	<div>
		<h1>Create a New Project</h1>
		
		<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="project-intro">
	<div class="container">
		<div class="row">
			<p><%=link_to "Back", projects_path %></p>
		</div>

		<div class="row">
			<div class="col-md-12 text-center">
				<h2><%= @project.title %></h2>
			</div>	
		</div>

		<div class="row">
			<div class="col-md-8">
				<%= image_tag @project.image_url, width: '100%', class: "img-responsive" %>
				<%= image_tag @project.image, width: '100%', class: "img-responsive" %>
			</div>
			
			<div class="col-md-4">	

				<% if user_signed_in?%>
				<% if @project.user_id == current_user.id %>
				<div class="project-mgmt">
					<%= link_to 'Edit',   edit_project_path(@project) %>
					<%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
				</div><!-- these links should only be visibible to admin_user with cancancan-->
				<%end%>
				<%end%>

				<div class="project-info">		
						<div class="project-bar">
							<div class="progress">
								<div class="progress-bar-sucess" role="progressbar" aria-valuenow="100%" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
							<span class="sr-only">100% Complete</span>
								</div>
							</div>
						</div>

						<div class="val">
								<p>100%<span>funded</span></p>
						<div>

					<div class="stats">
						<div class="row-stats">
							<div class="val">
								<p>$1000 <span>pledged</span></p>
							<div>
						
							<div class="val">
								<p>10 <span>days to go</span></p>
							<div>
						</div>
							
					</div>
			
				</div><!--it can be rendered as partial if wish-->
				<br><br><br>

				<div class="call-button text-center">
						
						<p><%= link_to 'Back this Project', new_project_pledge_path(@project), class: 'btn btn-success btn-lg btn-block' %></p><br>
						<p><%= link_to 'Offer a Skill', "#", class: 'btn btn-success btn-lg btn-block' %></p>
				</div>
	
			</div> <!-- end of project statistics details box-->
		</div>

	</div> <!--end of the container-->

	<div class="container">
			<div class="col-md-8">
					<p class="project-subtitle">Location:</p>						
					<p class="project-subtitle">Category: <%= @project.category.name %></p>
					<br>
					<p class="project-subtitle">About this project:</p>
					<p class="project-description"><%= @project.description %></p>
			</div><!--end of project details box-->

			<div class="col-md-4">
		
					


			</div>
	</div>

</div><!-- end of the wrap-->